const dictionary = [
  {id: "1", french: "le", english: "the; him, her, it, them"},
  {id: "2", french: "de", english: "some, any; of, from"},
  {id: "3", french: "un", english: "a, an; one"},
  {id: "4", french: "à", english: "to, at, in"},
  {id: "5", french: "être", english: "to be"},
  {id: "6", french: "et", english: "and"},
  {id: "7", french: "en", english: "in, by"},
  {id: "8", french: "avoir", english: "to have; assets"},
  {id: "9", french: "que", english: "that, which, who, whom"},
  {id: "10", french: "pour", english: "for, in order to "},
  {id: "11", french: "dans", english: "in, into, from"},
  {id: "12", french: "ce", english: "this, that"},
  {id: "13", french: "il", english: "he, it"},
  {id: "14", french: "qui", english: "who, whom"},
  {id: "15", french: "ne", english: "not"},
  {id: "16", french: "sur", english: "on, upon"},
  {id: "17", french: "se", english: "oneself, himself, herself, itself, themselves"},
  {id: "18", french: "pas", english: "not"},
  {id: "19", french: "plus", english: "more, no more"},
  {id: "20", french: "pouvoir", english: "to be able to, can"},
  {id: "21", french: "par", english: "by"},
  {id: "22", french: "je", english: "I"},
  {id: "23", french: "avec", english: "with"},
  {id: "24", french: "tout", english: "all, very"},
  {id: "25", french: "faire", english: "to do, make"},
  {id: "26", french: "son", english: "his, her, its"},
  {id: "27", french: "mettre", english: "to put, place"},
  {id: "28", french: "autre", english: "other"},
  {id: "29", french: "on", english: "one, we"},
  {id: "30", french: "mais", english: "but"},
  {id: "31", french: "nous", english: "we, us"},
  {id: "32", french: "comme", english: "like, as"},
  {id: "33", french: "ou", english: "or"},
  {id: "34", french: "si", english: "if, whether"},
  {id: "35", french: "leur", english: "their, theirs, them"},
  {id: "36", french: "y", english: "there; it"},
  {id: "37", french: "dire", english: "to say"},
  {id: "38", french: "elle", english: "she, her"},
  {id: "39", french: "devoir", english: "to have to"},
  {id: "40", french: "avant", english: "before; front"},
  {id: "41", french: "deux", english: "two"},
  {id: "42", french: "même", english: "same; even "},
  {id: "43", french: "prendre", english: "to take"},
  {id: "44", french: "aussi", english: "to, also; as"},
  {id: "45", french: "celui", english: "that, the one, he, him"},
  {id: "46", french: "donner", english: "to give"},
  {id: "47", french: "bien", english: "well; good"},
  {id: "48", french: "où", english: "where"},
  {id: "49", french: "fois", english: "time(s)"},
  {id: "50", french: "vous", english: "you"},
  {id: "51", french: "encore", english: "again, yet"},
  {id: "52", french: "nouveau", english: "new"},
  {id: "53", french: "aller", english: "to go"},
  {id: "54", french: "cela", english: "that, it"},
  {id: "55", french: "entre", english: "between"},
  {id: "56", french: "premier", english: "first"},
  {id: "57", french: "vouloir", english: "to want; will"},
  {id: "58", french: "déjà", english: "already"},
  {id: "59", french: "grand", english: "great, big, tall"},
  {id: "60", french: "mon", english: "my"},
  {id: "61", french: "me", english: "me, to me, myself "},
  {id: "62", french: "moins", english: "less; minus"},
  {id: "63", french: "aucun", english: "none, either, neither"},
  {id: "64", french: "lui", english: "him, her"},
  {id: "65", french: "temps", english: "time"},
  {id: "66", french: "très", english: "very"},
  {id: "67", french: "savoir", english: "to know"},
  {id: "68", french: "falloir", english: "to take, require, need"},
  {id: "69", french: "voir", english: "to see"},
  {id: "70", french: "quelque", english: "some"},
  {id: "71", french: "sans", english: "without"},
  {id: "72", french: "raison", english: "reason"},
  {id: "73", french: "notre", english: "our"},
  {id: "74", french: "dont", english: "whose, of which"},
  {id: "75", french: "non", english: "no, not"},
  {id: "76", french: "an", english: "year"},
  {id: "77", french: "monde", english: "world, people"},
  {id: "78", french: "jour", english: "day"},
  {id: "79", french: "monsieur", english: "mister, sir, gentleman"},
  {id: "80", french: "demander", english: "to ask for"},
  {id: "81", french: "alors", english: "then, so"},
  {id: "82", french: "après", english: "after"},
  {id: "83", french: "trouver", english: "to find"},
  {id: "84", french: "personne", english: "anyone, nobody"},
  {id: "85", french: "rendre", english: "to render, return, yield, give up"},
  {id: "86", french: "part", english: "share"},
  {id: "87", french: "dernier", english: "last"},
  {id: "88", french: "venir", english: "to come"},
  {id: "89", french: "pendant", english: "during"},
  {id: "90", french: "passer", english: "to pass"},
  {id: "91", french: "peu", english: "little"},
  {id: "92", french: "lequel", english: "who, whom, which"},
  {id: "93", french: "suite", english: "result, follow-up"},
  {id: "94", french: "bon", english: "good"},
  {id: "95", french: "comprendre", english: "to understand"},
  {id: "96", french: "depuis", english: "since "},
  {id: "97", french: "point", english: "at all"},
  {id: "98", french: "ainsi", english: "thus"},
  {id: "99", french: "heure", english: "hour"},
  {id: "100", french: "rester", english: "to stay"},
]

function randomWord() {
  return dictionary[Math.floor(Math.random()*dictionary.length)]
}

export { randomWord , dictionary }